Patch & Ragdoll
SynapseSL/Synapse pull request #70
Opened 2021-08-23 17:39 UTC by warquys

Patch the interface bug when published of the SynapseInjector. The interface become a class when it was published.
Add roleID and RoleType on the Ragdoll and add oldRoleID on the player. Add a new method AnnounceScpDeath on Map for annonce the Death of a SCP with a raison.

2021-08-23 17:52 UTC, AlmightyLks commented
Mind proving the fix for the interface / class bug?

2021-08-23 21:44 UTC, warquys commented
no problem
I post cella on discord because it will be easier

2021-08-24 12:40 UTC, GrafDimenzio commented
The change in the Loader so that the interfaces are actually interfaces is a good addition, but the other things aren't completely thought through

2021-09-01 22:23 UTC, warquys commented
I was fix it tomorrow

2021-09-02 10:10 UTC, AlmightyLks commented
> ScpRecon_**f**_Type

2021-09-02 10:17 UTC, warquys commented
> ScpRecon_f_Type ?

2021-09-04 22:09 UTC, AlmightyLks requested changes

2021-09-04 22:09 UTC, AlmightyLks commented on Synapse/Api/Enum/ScpReconfType.cs
> +        ByCdp = 4,
Would prefer the "By" to be removed

2021-09-04 22:09 UTC, AlmightyLks commented on Synapse/Api/Enum/ScpReconfType.cs
> +        ByUnknown = 8
Read above

2021-09-04 22:09 UTC, AlmightyLks commented on Synapse/Api/Enum/ScpReconfType.cs
> +    public enum ScpReconfType
`ScpReconfType` -> `ScpRecontainmentType`
1. Typo
2. Don't be shy to type out stuff, "Recon" is a bit eh

2021-09-04 22:09 UTC, AlmightyLks commented on Synapse/Api/Map.cs
> +            }
You may want to consider using a switch-assignment, see https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions

2021-09-04 22:09 UTC, AlmightyLks commented on Synapse/Api/Ragdoll.cs
> +            get => Server.Get.Host.ClassManager.Classes.FirstOrDefault(role => role.classColor == ragdoll.owner.ClassColor).roleId;
How does the color of a class define what roletype a ragdoll is?
Also, isn't the classcolor the one from spectator, or whatever they are at the point _after_ dropping a ragdoll?

2021-09-04 22:09 UTC, AlmightyLks commented on Synapse/SynapseExtensions.cs
> +    public static ScpReconfType GetScpReconfType(this PlayerStats.HitInfo info)
Same naming change applies

2021-09-04 22:09 UTC, AlmightyLks commented on Synapse/Api/Enum/ScpReconfType.cs
> +        ByCdp = 4,
@GrafDimenzio , opinion?

2021-09-05 10:59 UTC, warquys commented on Synapse/Api/Enum/ScpReconfType.cs
> +        ByCdp = 4,
I think you're right

2021-09-05 13:31 UTC, warquys commented
I made the changes you advised me

2021-09-09 18:03 UTC, merged